name: Deploy React App to Hostinger via FTP

on:
  push:
    branches:
      - main # Substitua pela sua branch de deploy, se diferente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Ajustar permissão do vite
        run: chmod +x ./node_modules/.bin/vite

      - name: Build React app
        run: npx vite build

      - name: Deploy to Hostinger via FTP

        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }} # aqui: 46.17.175.80
          username: ${{ secrets.FTP_USERNAME }} # u164307256
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_PATH }} # public_html/
          local-dir: dist/
          dangerous-clean-slate: true
